const { GameRTPLevel } = require("./GameRtpLevel");
 console.log("used base reel 1");
const {AA,BB,CC,DD,EE,FF,GG,HH,II,JJ,WD} = require("./GameReelSymbol").GameReelSymbol.symbols;

let baseGameReels1 = new Map();

baseGameReels1.set(GameRTPLevel.RTP_60, new Map());
baseGameReels1.get(GameRTPLevel.RTP_60).set(1, [CC, FF, EE, CC, DD, DD, FF, FF, FF, FF, EE, FF, EE, EE, CC, DD, DD, FF, AA, EE, DD, EE, FF, BB, CC, AA, EE, FF, DD, FF, FF, EE, DD, BB, FF, EE, BB, EE, DD, FF, CC, DD, DD, DD, EE, FF, FF, FF, CC, DD, FF, FF, FF, AA, BB, FF, FF, DD, FF, DD, FF, FF, EE, DD, FF, EE, CC, FF, EE, FF, EE, DD, EE, EE, CC, CC, DD, EE, EE, BB, DD, FF, DD, DD, FF, CC, FF, FF, FF, EE, EE, EE, CC, EE, EE, CC, CC, DD, DD, CC, FF, EE, DD, AA, FF, CC, AA, EE, DD, EE, EE, BB, JJ, EE, AA, EE, DD, EE, FF, AA, EE, BB, FF, DD, EE, DD, BB, EE, CC, EE, EE, BB, DD, CC, FF, EE, EE, FF, EE, FF, FF, BB, EE, DD, EE, DD, BB, EE, CC, BB, EE, EE, EE, EE, DD, FF, EE, BB, FF, EE, FF, AA, FF, EE, DD, FF, AA, FF, EE, CC, DD, FF, BB, HH, EE, FF, CC, DD, FF, EE, FF, FF, FF, EE, FF, BB, FF, DD, CC, CC, AA, EE, CC, FF, FF, EE, FF, DD, AA, CC, BB, BB, FF, FF, DD, EE, EE, FF, FF, EE, EE, AA, BB, EE, FF, FF, EE, EE, BB, FF, CC, EE, DD, DD, BB, EE, FF, AA, DD, FF, AA, DD, DD, CC, DD, FF, CC, BB, CC, CC, FF, AA, BB, FF, EE, CC, CC, EE, AA, AA, DD, EE, DD, BB, EE, EE, DD, FF, BB, FF, DD, FF, EE, FF, FF, FF, FF, CC, CC, FF, EE, CC, FF, BB, FF, EE, FF, DD, DD, FF, BB, FF, CC, CC, CC, FF, DD, FF, FF, FF, CC, DD, EE, DD, FF, AA, FF, FF, BB, CC, BB, EE, FF, FF, BB, EE, CC, DD, FF, EE, CC, EE, DD, DD, EE, BB, DD, AA, FF, CC, DD, BB, CC, EE, FF, AA, AA, CC, DD, CC, EE, EE, CC, CC, EE, FF, BB, DD, BB, CC, BB, DD, FF, FF, EE, BB, DD, FF, EE, BB, CC, DD, DD, BB, AA, EE, DD, DD, DD, AA, BB, CC, BB, FF, BB, FF, EE, DD, EE, DD, EE, FF, CC, DD, EE, FF, BB, DD, FF, CC, DD, BB, DD, CC, CC, AA, FF, CC, FF, CC, DD, GG, DD, DD, DD, EE, DD, FF, DD, AA, EE, FF, EE, DD, BB, FF, EE, II, FF, FF, DD, EE, CC, FF, DD, BB, EE, BB, CC, FF, CC, EE, DD, DD, EE, BB, BB, CC, DD, FF, FF, CC, DD, CC, AA, CC, EE, BB, BB, EE, FF, EE, FF, BB, DD, CC, FF, EE, CC, FF, FF, EE, FF, FF, CC, CC, EE, EE, CC, DD, EE, AA, FF, EE, DD, FF, AA, FF, FF, DD, FF, FF, DD, AA, EE, FF, FF, AA, FF, CC, CC, EE, EE, EE]);
baseGameReels1.get(GameRTPLevel.RTP_60).set(2, [JJ, II, GG, II, GG, JJ, JJ, JJ, JJ, JJ, JJ, HH, GG, II, HH, HH, HH, II, HH, HH, GG, JJ, JJ, HH, JJ, GG, JJ, II, WD, HH, HH, II, GG, II, II, HH, JJ, HH, II, HH, II, JJ, II, JJ, JJ, HH, JJ, II, HH, JJ, JJ, HH, JJ, GG, GG, II, GG, II, II, HH, GG, HH, II, GG, JJ, JJ, WD, HH, JJ, HH, GG, GG, JJ, JJ, HH, JJ, JJ, BB, HH, HH, JJ, II, II, II, JJ, JJ, II, GG, GG, GG, GG, II, HH, II, JJ, HH, DD, II, HH, II, JJ, GG, GG, II, II, HH, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, JJ, JJ, HH, GG, JJ, JJ, JJ, HH, II, II, GG, GG, JJ, JJ, II, JJ, GG, JJ, HH, HH, JJ, II, GG, JJ, HH, HH, II, HH, JJ, HH, HH, HH, HH, GG, II, JJ, HH, II, HH, II, II, II, GG, II, GG, JJ, HH, II, HH, GG, JJ, JJ, II, GG, II, JJ, HH, JJ, II, JJ, GG, GG, JJ, JJ, JJ, II, II, HH, II, JJ, GG, HH, JJ, HH, CC, JJ, HH, JJ, JJ, JJ, II, JJ, GG, JJ, II, JJ, HH, JJ, JJ, JJ, JJ, GG, HH, HH, JJ, GG, II, JJ, II, JJ, II, II, II, II, II, JJ, II, GG, GG, GG, JJ, II, GG, GG, II, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, II, II, HH, GG, JJ, HH, II, HH, HH, HH, II, GG, FF, II, JJ, HH, GG, JJ, WD, JJ, JJ, WD, II, JJ, JJ, II, JJ, JJ, JJ, EE, II, JJ, HH, JJ, II, HH, JJ, JJ, II, HH, JJ, II, JJ, JJ, II, II, II, HH, GG, HH, GG, JJ, II, II, JJ, GG, AA, HH, GG, GG, II, JJ, II, JJ, JJ, HH, II, II, II, GG, HH, II, GG, JJ, JJ, II, HH, II, II, JJ, JJ, HH, WD, HH, HH, JJ, II, HH, JJ, II, JJ, II]);
baseGameReels1.get(GameRTPLevel.RTP_60).set(3, [EE, FF, CC, DD, EE, EE, CC, CC, DD, BB, DD, DD, BB, EE, FF, FF, EE, EE, FF, BB, CC, FF, BB, FF, CC, EE, FF, EE, FF, FF, DD, EE, DD, BB, BB, FF, WD, FF, CC, FF, FF, EE, DD, BB, EE, EE, FF, EE, FF, FF, WD, FF, DD, FF, AA, BB, FF, EE, FF, BB, BB, EE, FF, AA, FF, BB, AA, AA, FF, FF, FF, FF, EE, CC, CC, FF, CC, CC, FF, FF, EE, FF, DD, CC, FF, DD, DD, CC, FF, AA, FF, DD, WD, EE, FF, DD, DD, CC, FF, EE, FF, BB, EE, FF, FF, CC, BB, FF, FF, CC, FF, FF, AA, EE, CC, FF, FF, CC, EE, CC, FF, BB, EE, EE, FF, DD, EE, BB, CC, DD, DD, FF, DD, BB, EE, FF, DD, FF, DD, FF, DD, EE, CC, DD, FF, BB, BB, FF, DD, AA, EE, EE, DD, AA, CC, DD, DD, FF, II, EE, CC, CC, BB, CC, EE, AA, EE, FF, AA, EE, CC, DD, FF, FF, CC, CC, DD, DD, AA, FF, AA, DD, FF, WD, DD, EE, BB, DD, FF, AA, EE, DD, DD, BB, DD, DD, EE, BB, CC, CC, FF, EE, FF, EE, FF, EE, FF, FF, FF, FF, BB, BB, BB, EE, AA, EE, FF, CC, FF, AA, FF, EE, DD, EE, CC, DD, FF, EE, CC, EE, FF, EE, CC, FF, EE, BB, HH, BB, DD, AA, AA, DD, JJ, FF, DD, EE, DD, CC, CC, FF, FF, EE, DD, FF, CC, FF, EE, EE, DD, DD, FF, CC, EE, BB, EE, BB, CC, FF, FF, FF, FF, DD, DD, BB, FF, BB, EE, EE, BB, EE, FF, EE, BB, FF, EE, AA, EE, DD, DD, EE, FF, EE, AA, CC, EE, CC, EE, CC, EE, CC, EE, EE, EE, CC, FF, DD, DD, EE, FF, FF, EE, EE, DD, DD, FF, FF, FF, EE, CC, FF, EE, DD, EE, EE, CC, FF, FF, EE, EE, BB, DD, EE, FF, FF, EE, FF, FF, FF, DD, EE, CC, CC, AA, AA, CC, DD, EE, CC, EE, EE, FF, EE, DD, CC, DD, CC, BB, EE, AA, CC, EE, DD, DD, FF, FF, EE, GG, EE, FF, FF, EE, FF, FF, EE, CC, BB, FF, DD, AA, BB, BB, AA, EE, EE, DD, DD, DD, CC, CC, EE, DD, FF, CC, FF, EE, AA, FF, BB, FF, FF, FF, CC, CC, DD, BB, FF, CC, CC, FF, EE, WD, CC, BB, EE, DD, EE, FF, FF, FF, CC, DD, DD, EE, CC, CC, EE, FF, DD, FF, EE, DD, FF, EE, AA, BB, CC, EE, FF, BB, BB, AA, DD, EE, DD, FF, DD, DD, EE, AA, CC, DD, DD, DD, DD, BB, CC, FF, DD, DD, AA, DD, DD, CC, EE, FF, CC, BB, BB, DD, AA, EE, DD, BB, DD, FF, EE, EE, BB, EE, EE, CC, FF, BB, DD, DD, EE, DD, FF, FF]);
baseGameReels1.get(GameRTPLevel.RTP_60).set(4, [JJ, JJ, II, GG, JJ, GG, HH, WD, JJ, HH, GG, II, GG, DD, HH, GG, JJ, JJ, II, II, II, HH, GG, II, JJ, II, HH, HH, GG, II, II, II, JJ, JJ, JJ, JJ, JJ, HH, JJ, GG, II, HH, HH, II, II, JJ, HH, JJ, II, JJ, II, HH, JJ, GG, GG, II, HH, HH, II, HH, GG, II, JJ, II, HH, JJ, JJ, JJ, HH, GG, JJ, JJ, II, GG, JJ, II, GG, JJ, JJ, JJ, JJ, EE, HH, GG, JJ, GG, HH, II, JJ, HH, JJ, JJ, JJ, HH, JJ, GG, HH, II, GG, JJ, JJ, II, II, HH, HH, WD, II, II, HH, JJ, JJ, JJ, II, JJ, GG, II, JJ, II, HH, II, II, JJ, II, JJ, GG, JJ, HH, II, WD, JJ, II, HH, JJ, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, II, HH, JJ, GG, II, CC, JJ, AA, II, II, HH, HH, HH, II, JJ, JJ, JJ, HH, JJ, GG, GG, GG, II, JJ, JJ, II, JJ, JJ, II, GG, GG, JJ, II, GG, BB, JJ, JJ, HH, II, II, JJ, JJ, II, II, II, II, GG, II, II, JJ, II, GG, II, GG, GG, II, II, II, II, GG, II, JJ, HH, HH, JJ, JJ, JJ, II, HH, JJ, WD, HH, II, II, GG, HH, GG, JJ, JJ, II, GG, II, II, JJ, II, HH, HH, HH, II, JJ, JJ, JJ, JJ, II, II, JJ, JJ, HH, JJ, HH, JJ, JJ, GG, JJ, HH, GG, HH, JJ, GG, II, JJ, II, JJ, II, GG, II, FF, JJ, HH, HH, GG, HH, HH, II, HH, WD, JJ, HH, GG, GG, HH, II, JJ, JJ, JJ, HH, HH, HH, JJ, II, JJ, JJ, GG, HH, II, JJ, II, HH, HH, JJ, II, GG, HH, GG, JJ, HH, JJ, HH, HH, JJ, II, II, II, HH, II, HH, JJ, JJ, HH, JJ, JJ, GG, HH, JJ, JJ, II, II, II, GG, HH, II, GG, II, GG, HH, JJ, JJ, HH, II, GG]);
baseGameReels1.get(GameRTPLevel.RTP_60).set(5, [BB, FF, WD, FF, FF, BB, DD, CC, AA, EE, BB, GG, FF, FF, II, CC, EE, FF, FF, CC, FF, FF, EE, EE, FF, EE, CC, AA, FF, DD, FF, AA, FF, DD, AA, DD, FF, FF, WD, CC, EE, EE, BB, DD, BB, AA, FF, FF, FF, FF, AA, EE, CC, FF, FF, FF, DD, EE, CC, DD, CC, EE, FF, DD, FF, EE, CC, AA, FF, DD, FF, EE, BB, CC, CC, AA, EE, DD, BB, EE, CC, DD, DD, FF, EE, DD, DD, EE, CC, AA, FF, CC, DD, FF, DD, FF, DD, FF, FF, CC, EE, BB, EE, DD, FF, FF, FF, AA, BB, EE, CC, DD, DD, FF, FF, EE, CC, EE, EE, FF, EE, FF, DD, FF, FF, DD, EE, EE, AA, FF, AA, FF, EE, EE, EE, EE, EE, EE, EE, FF, DD, EE, EE, FF, FF, BB, FF, DD, FF, CC, BB, EE, FF, CC, CC, EE, DD, BB, HH, FF, AA, DD, FF, EE, EE, EE, DD, FF, EE, CC, FF, EE, EE, WD, EE, EE, DD, BB, CC, EE, BB, EE, FF, EE, CC, EE, CC, BB, EE, AA, BB, EE, FF, FF, AA, EE, FF, FF, FF, CC, FF, DD, DD, AA, EE, FF, FF, CC, AA, BB, EE, CC, FF, FF, EE, CC, CC, EE, BB, DD, EE, FF, EE, DD, DD, AA, CC, FF, DD, FF, FF, EE, DD, CC, CC, FF, CC, CC, CC, FF, CC, CC, DD, EE, EE, CC, DD, CC, EE, FF, FF, EE, DD, BB, FF, FF, FF, CC, DD, FF, FF, FF, FF, FF, CC, FF, FF, EE, DD, EE, CC, FF, BB, DD, BB, DD, DD, FF, BB, FF, DD, FF, EE, CC, FF, BB, EE, FF, FF, BB, EE, CC, AA, CC, DD, FF, EE, DD, CC, EE, EE, DD, DD, FF, EE, FF, FF, CC, FF, AA, BB, AA, EE, FF, BB, DD, CC, EE, FF, CC, EE, EE, DD, EE, DD, DD, EE, CC, WD, EE, CC, DD, DD, AA, BB, BB, AA, AA, BB, EE, EE, FF, EE, FF, DD, DD, BB, CC, EE, EE, BB, FF, EE, BB, DD, FF, BB, EE, BB, DD, FF, EE, CC, DD, FF, DD, DD, BB, BB, AA, BB, BB, EE, BB, CC, FF, DD, BB, DD, FF, BB, FF, AA, FF, CC, AA, CC, FF, EE, DD, CC, DD, CC, EE, BB, FF, CC, EE, EE, CC, EE, FF, FF, DD, FF, AA, EE, DD, CC, FF, BB, DD, DD, FF, DD, CC, FF, EE, WD, DD, EE, EE, DD, DD, DD, EE, DD, FF, DD, FF, FF, BB, FF, EE, FF, EE, FF, DD, DD, DD, FF, EE, EE, BB, EE, FF, EE, CC, AA, EE, EE, FF, DD, BB, BB, DD, BB, CC, FF, EE, FF, CC, DD, CC, EE, FF, AA, DD, DD, DD, FF, BB, BB, CC, EE, JJ, FF, EE, EE, CC, CC, CC, FF, DD, DD, FF, DD, DD, DD]);
baseGameReels1.get(GameRTPLevel.RTP_60).set(6, [JJ, JJ, JJ, JJ, HH, HH, HH, II, JJ, AA, GG, HH, GG, JJ, II, HH, JJ, JJ, II, HH, HH, HH, JJ, JJ, JJ, GG, JJ, JJ, HH, II, II, JJ, GG, II, JJ, HH, JJ, HH, GG, GG, II, II, II, II, HH, HH, JJ, EE, GG, II, II, GG, JJ, JJ, II, HH, II, JJ, II, II, JJ, HH, GG, GG, HH, GG, II, JJ, JJ, JJ, JJ, HH, GG, II, GG, JJ, HH, II, HH, II, JJ, JJ, HH, II, GG, GG, II, HH, HH, HH, GG, JJ, II, II, HH, II, JJ, JJ, HH, HH, JJ, HH, HH, II, JJ, HH, II, II, II, HH, II, II, II, II, HH, II, JJ, HH, GG, JJ, II, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, GG, II, JJ, HH, HH, JJ, GG, CC, II, JJ, II, II, II, JJ, II, GG, HH, HH, BB, HH, JJ, GG, HH, JJ, GG, II, II, JJ, II, JJ, HH, II, JJ, II, GG, II, II, GG, II, GG, JJ, JJ, HH, JJ, JJ, JJ, II, HH, II, JJ, II, JJ, JJ, GG, GG, HH, II, HH, HH, HH, GG, JJ, JJ, HH, HH, HH, II, II, GG, GG, HH, II, JJ, JJ, JJ, GG, GG, II, JJ, HH, JJ, JJ, GG, II, II, DD, JJ, JJ, II, II, JJ, JJ, JJ, HH, HH, JJ, II, JJ, JJ, II, JJ, II, JJ, II, JJ, II, GG, GG, JJ, GG, JJ, II, JJ, JJ, JJ, HH, II, HH, JJ, JJ, GG, GG, II, II, II, GG, II, II, HH, JJ, II, JJ, HH, GG, GG, HH, GG, HH, II, JJ, II, JJ, JJ, HH, HH, GG, II, JJ, II, HH, GG, GG, JJ, JJ, GG, HH, HH, GG, JJ, GG, II, II, JJ, HH, GG, II, JJ, JJ, JJ, JJ, II, JJ, II, JJ, JJ, JJ, HH, II, HH, II, JJ, II, HH, JJ, HH, II, JJ, HH, II, JJ, JJ, JJ, JJ, II, FF, GG, JJ]);
 
baseGameReels1.set(GameRTPLevel.RTP_70, new Map()); 
baseGameReels1.get(GameRTPLevel.RTP_70).set(1, [CC, FF, EE, CC, DD, DD, FF, FF, FF, FF, EE, FF, EE, EE, CC, DD, DD, FF, AA, EE, DD, EE, FF, BB, CC, AA, EE, FF, DD, FF, FF, EE, DD, BB, FF, EE, BB, EE, DD, FF, CC, DD, DD, DD, EE, FF, FF, FF, CC, DD, FF, FF, FF, AA, BB, FF, FF, DD, FF, DD, FF, FF, EE, DD, FF, EE, CC, FF, EE, FF, EE, DD, EE, EE, CC, CC, DD, EE, EE, BB, DD, FF, DD, DD, FF, CC, FF, FF, FF, EE, EE, EE, CC, EE, EE, CC, CC, DD, DD, CC, FF, EE, DD, AA, FF, CC, AA, EE, DD, EE, EE, BB, JJ, EE, AA, EE, DD, EE, FF, AA, EE, BB, FF, DD, EE, DD, BB, EE, CC, EE, EE, BB, DD, CC, FF, EE, EE, FF, EE, FF, FF, BB, EE, DD, EE, DD, BB, EE, CC, BB, EE, EE, EE, EE, DD, FF, EE, BB, FF, EE, FF, AA, FF, EE, DD, FF, AA, FF, EE, CC, DD, FF, BB, HH, EE, FF, CC, DD, FF, EE, FF, FF, FF, EE, FF, BB, FF, DD, CC, CC, AA, EE, CC, FF, FF, EE, FF, DD, AA, CC, BB, BB, FF, FF, DD, EE, EE, FF, FF, EE, EE, AA, BB, EE, FF, FF, EE, EE, BB, FF, CC, EE, DD, DD, BB, EE, FF, AA, DD, FF, AA, DD, DD, CC, DD, FF, CC, BB, CC, CC, FF, AA, BB, FF, EE, CC, CC, EE, AA, AA, DD, EE, DD, BB, EE, EE, DD, FF, BB, FF, DD, FF, EE, FF, FF, FF, FF, CC, CC, FF, EE, CC, FF, BB, FF, EE, FF, DD, DD, FF, BB, FF, CC, CC, CC, FF, DD, FF, FF, FF, CC, DD, EE, DD, FF, AA, FF, FF, BB, CC, BB, EE, FF, FF, BB, EE, CC, DD, FF, EE, CC, EE, DD, DD, EE, BB, DD, AA, FF, CC, DD, BB, CC, EE, FF, AA, AA, CC, DD, CC, EE, EE, CC, CC, EE, FF, BB, DD, BB, CC, BB, DD, FF, FF, EE, BB, DD, FF, EE, BB, CC, DD, DD, BB, AA, EE, DD, DD, DD, AA, BB, CC, BB, FF, BB, FF, EE, DD, EE, DD, EE, FF, CC, DD, EE, FF, BB, DD, FF, CC, DD, BB, DD, CC, CC, AA, FF, CC, FF, CC, DD, GG, DD, DD, DD, EE, DD, FF, DD, AA, EE, FF, EE, DD, BB, FF, EE, II, FF, FF, DD, EE, CC, FF, DD, BB, EE, BB, CC, FF, CC, EE, DD, DD, EE, BB, BB, CC, DD, FF, FF, CC, DD, CC, AA, CC, EE, BB, BB, EE, FF, EE, FF, BB, DD, CC, FF, EE, CC, FF, FF, EE, FF, FF, CC, CC, EE, EE, CC, DD, EE, AA, FF, EE, DD, FF, AA, FF, FF, DD, FF, FF, DD, AA, EE, FF, FF, AA, FF, CC, CC, EE, EE, EE]);
baseGameReels1.get(GameRTPLevel.RTP_70).set(2, [JJ, II, GG, II, GG, JJ, JJ, JJ, JJ, JJ, JJ, HH, GG, II, HH, HH, HH, II, HH, HH, GG, JJ, JJ, HH, JJ, GG, JJ, II, WD, HH, HH, II, GG, II, II, HH, JJ, HH, II, HH, II, JJ, II, JJ, JJ, HH, JJ, II, HH, JJ, JJ, HH, JJ, GG, GG, II, GG, II, II, HH, GG, HH, II, GG, JJ, JJ, WD, HH, JJ, HH, GG, GG, JJ, JJ, HH, JJ, JJ, BB, HH, HH, JJ, II, II, II, JJ, JJ, II, GG, GG, GG, GG, II, HH, II, JJ, HH, DD, II, HH, II, JJ, GG, GG, II, II, HH, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, JJ, JJ, HH, GG, JJ, JJ, JJ, HH, II, II, GG, GG, JJ, JJ, II, JJ, GG, JJ, HH, HH, JJ, II, GG, JJ, HH, HH, II, HH, JJ, HH, HH, HH, HH, GG, II, JJ, HH, II, HH, II, II, II, GG, II, GG, JJ, HH, II, HH, GG, JJ, JJ, II, GG, II, JJ, HH, JJ, II, JJ, GG, GG, JJ, JJ, JJ, II, II, HH, II, JJ, GG, HH, JJ, HH, CC, JJ, HH, JJ, JJ, JJ, II, JJ, GG, JJ, II, JJ, HH, JJ, JJ, JJ, JJ, GG, HH, HH, JJ, GG, II, JJ, II, JJ, II, II, II, II, II, JJ, II, GG, GG, GG, JJ, II, GG, GG, II, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, II, II, HH, GG, JJ, HH, II, HH, HH, HH, II, GG, FF, II, JJ, HH, GG, JJ, WD, JJ, JJ, WD, II, JJ, JJ, II, JJ, JJ, JJ, EE, II, JJ, HH, JJ, II, HH, JJ, JJ, II, HH, JJ, II, JJ, JJ, II, II, II, HH, GG, HH, GG, JJ, II, II, JJ, GG, AA, HH, GG, GG, II, JJ, II, JJ, JJ, HH, II, II, II, GG, HH, II, GG, JJ, JJ, II, HH, II, II, JJ, JJ, HH, WD, HH, HH, JJ, II, HH, JJ, II, JJ, II]);
baseGameReels1.get(GameRTPLevel.RTP_70).set(3, [EE, FF, CC, DD, EE, EE, CC, CC, DD, BB, DD, DD, BB, EE, FF, FF, EE, EE, FF, BB, CC, FF, BB, FF, CC, EE, FF, EE, FF, FF, DD, EE, DD, BB, BB, FF, WD, FF, CC, FF, FF, EE, DD, BB, EE, EE, FF, EE, FF, FF, WD, FF, DD, FF, AA, BB, FF, EE, FF, BB, BB, EE, FF, AA, FF, BB, AA, AA, FF, FF, FF, FF, EE, CC, CC, FF, CC, CC, FF, FF, EE, FF, DD, CC, FF, DD, DD, CC, FF, AA, FF, DD, WD, EE, FF, DD, DD, CC, FF, EE, FF, BB, EE, FF, FF, CC, BB, FF, FF, CC, FF, FF, AA, EE, CC, FF, FF, CC, EE, CC, FF, BB, EE, EE, FF, DD, EE, BB, CC, DD, DD, FF, DD, BB, EE, FF, DD, FF, DD, FF, DD, EE, CC, DD, FF, BB, BB, FF, DD, AA, EE, EE, DD, AA, CC, DD, DD, FF, II, EE, CC, CC, BB, CC, EE, AA, EE, FF, AA, EE, CC, DD, FF, FF, CC, CC, DD, DD, AA, FF, AA, DD, FF, WD, DD, EE, BB, DD, FF, AA, EE, DD, DD, BB, DD, DD, EE, BB, CC, CC, FF, EE, FF, EE, FF, EE, FF, FF, FF, FF, BB, BB, BB, EE, AA, EE, FF, CC, FF, AA, FF, EE, DD, EE, CC, DD, FF, EE, CC, EE, FF, EE, CC, FF, EE, BB, HH, BB, DD, AA, AA, DD, JJ, FF, DD, EE, DD, CC, CC, FF, FF, EE, DD, FF, CC, FF, EE, EE, DD, DD, FF, CC, EE, BB, EE, BB, CC, FF, FF, FF, FF, DD, DD, BB, FF, BB, EE, EE, BB, EE, FF, EE, BB, FF, EE, AA, EE, DD, DD, EE, FF, EE, AA, CC, EE, CC, EE, CC, EE, CC, EE, EE, EE, CC, FF, DD, DD, EE, FF, FF, EE, EE, DD, DD, FF, FF, FF, EE, CC, FF, EE, DD, EE, EE, CC, FF, FF, EE, EE, BB, DD, EE, FF, FF, EE, FF, FF, FF, DD, EE, CC, CC, AA, AA, CC, DD, EE, CC, EE, EE, FF, EE, DD, CC, DD, CC, BB, EE, AA, CC, EE, DD, DD, FF, FF, EE, GG, EE, FF, FF, EE, FF, FF, EE, CC, BB, FF, DD, AA, BB, BB, AA, EE, EE, DD, DD, DD, CC, CC, EE, DD, FF, CC, FF, EE, AA, FF, BB, FF, FF, FF, CC, CC, DD, BB, FF, CC, CC, FF, EE, WD, CC, BB, EE, DD, EE, FF, FF, FF, CC, DD, DD, EE, CC, CC, EE, FF, DD, FF, EE, DD, FF, EE, AA, BB, CC, EE, FF, BB, BB, AA, DD, EE, DD, FF, DD, DD, EE, AA, CC, DD, DD, DD, DD, BB, CC, FF, DD, DD, AA, DD, DD, CC, EE, FF, CC, BB, BB, DD, AA, EE, DD, BB, DD, FF, EE, EE, BB, EE, EE, CC, FF, BB, DD, DD, EE, DD, FF, FF]);
baseGameReels1.get(GameRTPLevel.RTP_70).set(4, [JJ, JJ, II, GG, JJ, GG, HH, WD, JJ, HH, GG, II, GG, DD, HH, GG, JJ, JJ, II, II, II, HH, GG, II, JJ, II, HH, HH, GG, II, II, II, JJ, JJ, JJ, JJ, JJ, HH, JJ, GG, II, HH, HH, II, II, JJ, HH, JJ, II, JJ, II, HH, JJ, GG, GG, II, HH, HH, II, HH, GG, II, JJ, II, HH, JJ, JJ, JJ, HH, GG, JJ, JJ, II, GG, JJ, II, GG, JJ, JJ, JJ, JJ, EE, HH, GG, JJ, GG, HH, II, JJ, HH, JJ, JJ, JJ, HH, JJ, GG, HH, II, GG, JJ, JJ, II, II, HH, HH, WD, II, II, HH, JJ, JJ, JJ, II, JJ, GG, II, JJ, II, HH, II, II, JJ, II, JJ, GG, JJ, HH, II, WD, JJ, II, HH, JJ, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, II, HH, JJ, GG, II, CC, JJ, AA, II, II, HH, HH, HH, II, JJ, JJ, JJ, HH, JJ, GG, GG, GG, II, JJ, JJ, II, JJ, JJ, II, GG, GG, JJ, II, GG, BB, JJ, JJ, HH, II, II, JJ, JJ, II, II, II, II, GG, II, II, JJ, II, GG, II, GG, GG, II, II, II, II, GG, II, JJ, HH, HH, JJ, JJ, JJ, II, HH, JJ, WD, HH, II, II, GG, HH, GG, JJ, JJ, II, GG, II, II, JJ, II, HH, HH, HH, II, JJ, JJ, JJ, JJ, II, II, JJ, JJ, HH, JJ, HH, JJ, JJ, GG, JJ, HH, GG, HH, JJ, GG, II, JJ, II, JJ, II, GG, II, FF, JJ, HH, HH, GG, HH, HH, II, HH, WD, JJ, HH, GG, GG, HH, II, JJ, JJ, JJ, HH, HH, HH, JJ, II, JJ, JJ, GG, HH, II, JJ, II, HH, HH, JJ, II, GG, HH, GG, JJ, HH, JJ, HH, HH, JJ, II, II, II, HH, II, HH, JJ, JJ, HH, JJ, JJ, GG, HH, JJ, JJ, II, II, II, GG, HH, II, GG, II, GG, HH, JJ, JJ, HH, II, GG]);
baseGameReels1.get(GameRTPLevel.RTP_70).set(5, [BB, FF, WD, FF, FF, BB, DD, CC, AA, EE, BB, GG, FF, FF, II, CC, EE, FF, FF, CC, FF, FF, EE, EE, FF, EE, CC, AA, FF, DD, FF, AA, FF, DD, AA, DD, FF, FF, WD, CC, EE, EE, BB, DD, BB, AA, FF, FF, FF, FF, AA, EE, CC, FF, FF, FF, DD, EE, CC, DD, CC, EE, FF, DD, FF, EE, CC, AA, FF, DD, FF, EE, BB, CC, CC, AA, EE, DD, BB, EE, CC, DD, DD, FF, EE, DD, DD, EE, CC, AA, FF, CC, DD, FF, DD, FF, DD, FF, FF, CC, EE, BB, EE, DD, FF, FF, FF, AA, BB, EE, CC, DD, DD, FF, FF, EE, CC, EE, EE, FF, EE, FF, DD, FF, FF, DD, EE, EE, AA, FF, AA, FF, EE, EE, EE, EE, EE, EE, EE, FF, DD, EE, EE, FF, FF, BB, FF, DD, FF, CC, BB, EE, FF, CC, CC, EE, DD, BB, HH, FF, AA, DD, FF, EE, EE, EE, DD, FF, EE, CC, FF, EE, EE, WD, EE, EE, DD, BB, CC, EE, BB, EE, FF, EE, CC, EE, CC, BB, EE, AA, BB, EE, FF, FF, AA, EE, FF, FF, FF, CC, FF, DD, DD, AA, EE, FF, FF, CC, AA, BB, EE, CC, FF, FF, EE, CC, CC, EE, BB, DD, EE, FF, EE, DD, DD, AA, CC, FF, DD, FF, FF, EE, DD, CC, CC, FF, CC, CC, CC, FF, CC, CC, DD, EE, EE, CC, DD, CC, EE, FF, FF, EE, DD, BB, FF, FF, FF, CC, DD, FF, FF, FF, FF, FF, CC, FF, FF, EE, DD, EE, CC, FF, BB, DD, BB, DD, DD, FF, BB, FF, DD, FF, EE, CC, FF, BB, EE, FF, FF, BB, EE, CC, AA, CC, DD, FF, EE, DD, CC, EE, EE, DD, DD, FF, EE, FF, FF, CC, FF, AA, BB, AA, EE, FF, BB, DD, CC, EE, FF, CC, EE, EE, DD, EE, DD, DD, EE, CC, WD, EE, CC, DD, DD, AA, BB, BB, AA, AA, BB, EE, EE, FF, EE, FF, DD, DD, BB, CC, EE, EE, BB, FF, EE, BB, DD, FF, BB, EE, BB, DD, FF, EE, CC, DD, FF, DD, DD, BB, BB, AA, BB, BB, EE, BB, CC, FF, DD, BB, DD, FF, BB, FF, AA, FF, CC, AA, CC, FF, EE, DD, CC, DD, CC, EE, BB, FF, CC, EE, EE, CC, EE, FF, FF, DD, FF, AA, EE, DD, CC, FF, BB, DD, DD, FF, DD, CC, FF, EE, WD, DD, EE, EE, DD, DD, DD, EE, DD, FF, DD, FF, FF, BB, FF, EE, FF, EE, FF, DD, DD, DD, FF, EE, EE, BB, EE, FF, EE, CC, AA, EE, EE, FF, DD, BB, BB, DD, BB, CC, FF, EE, FF, CC, DD, CC, EE, FF, AA, DD, DD, DD, FF, BB, BB, CC, EE, JJ, FF, EE, EE, CC, CC, CC, FF, DD, DD, FF, DD, DD, DD]);
baseGameReels1.get(GameRTPLevel.RTP_70).set(6, [JJ, JJ, JJ, JJ, HH, HH, HH, II, JJ, AA, GG, HH, GG, JJ, II, HH, JJ, JJ, II, HH, HH, HH, JJ, JJ, JJ, GG, JJ, JJ, HH, II, II, JJ, GG, II, JJ, HH, JJ, HH, GG, GG, II, II, II, II, HH, HH, JJ, EE, GG, II, II, GG, JJ, JJ, II, HH, II, JJ, II, II, JJ, HH, GG, GG, HH, GG, II, JJ, JJ, JJ, JJ, HH, GG, II, GG, JJ, HH, II, HH, II, JJ, JJ, HH, II, GG, GG, II, HH, HH, HH, GG, JJ, II, II, HH, II, JJ, JJ, HH, HH, JJ, HH, HH, II, JJ, HH, II, II, II, HH, II, II, II, II, HH, II, JJ, HH, GG, JJ, II, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, GG, II, JJ, HH, HH, JJ, GG, CC, II, JJ, II, II, II, JJ, II, GG, HH, HH, BB, HH, JJ, GG, HH, JJ, GG, II, II, JJ, II, JJ, HH, II, JJ, II, GG, II, II, GG, II, GG, JJ, JJ, HH, JJ, JJ, JJ, II, HH, II, JJ, II, JJ, JJ, GG, GG, HH, II, HH, HH, HH, GG, JJ, JJ, HH, HH, HH, II, II, GG, GG, HH, II, JJ, JJ, JJ, GG, GG, II, JJ, HH, JJ, JJ, GG, II, II, DD, JJ, JJ, II, II, JJ, JJ, JJ, HH, HH, JJ, II, JJ, JJ, II, JJ, II, JJ, II, JJ, II, GG, GG, JJ, GG, JJ, II, JJ, JJ, JJ, HH, II, HH, JJ, JJ, GG, GG, II, II, II, GG, II, II, HH, JJ, II, JJ, HH, GG, GG, HH, GG, HH, II, JJ, II, JJ, JJ, HH, HH, GG, II, JJ, II, HH, GG, GG, JJ, JJ, GG, HH, HH, GG, JJ, GG, II, II, JJ, HH, GG, II, JJ, JJ, JJ, JJ, II, JJ, II, JJ, JJ, JJ, HH, II, HH, II, JJ, II, HH, JJ, HH, II, JJ, HH, II, JJ, JJ, JJ, JJ, II, FF, GG, JJ]);

baseGameReels1.set(GameRTPLevel.RTP_80, new Map());
baseGameReels1.get(GameRTPLevel.RTP_80).set(1, [CC, FF, EE, CC, DD, DD, FF, FF, FF, FF, EE, FF, EE, EE, CC, DD, DD, FF, AA, EE, DD, EE, FF, BB, CC, AA, EE, FF, DD, FF, FF, EE, DD, BB, FF, EE, BB, EE, DD, FF, CC, DD, DD, DD, EE, FF, FF, FF, CC, DD, FF, FF, FF, AA, BB, FF, FF, DD, FF, DD, FF, FF, EE, DD, FF, EE, CC, FF, EE, FF, EE, DD, EE, EE, CC, CC, DD, EE, EE, BB, DD, FF, DD, DD, FF, CC, FF, FF, FF, EE, EE, EE, CC, EE, EE, CC, CC, DD, DD, CC, FF, EE, DD, AA, FF, CC, AA, EE, DD, EE, EE, BB, JJ, EE, AA, EE, DD, EE, FF, AA, EE, BB, FF, DD, EE, DD, BB, EE, CC, EE, EE, BB, DD, CC, FF, EE, EE, FF, EE, FF, FF, BB, EE, DD, EE, DD, BB, EE, CC, BB, EE, EE, EE, EE, DD, FF, EE, BB, FF, EE, FF, AA, FF, EE, DD, FF, AA, FF, EE, CC, DD, FF, BB, HH, EE, FF, CC, DD, FF, EE, FF, FF, FF, EE, FF, BB, FF, DD, CC, CC, AA, EE, CC, FF, FF, EE, FF, DD, AA, CC, BB, BB, FF, FF, DD, EE, EE, FF, FF, EE, EE, AA, BB, EE, FF, FF, EE, EE, BB, FF, CC, EE, DD, DD, BB, EE, FF, AA, DD, FF, AA, DD, DD, CC, DD, FF, CC, BB, CC, CC, FF, AA, BB, FF, EE, CC, CC, EE, AA, AA, DD, EE, DD, BB, EE, EE, DD, FF, BB, FF, DD, FF, EE, FF, FF, FF, FF, CC, CC, FF, EE, CC, FF, BB, FF, EE, FF, DD, DD, FF, BB, FF, CC, CC, CC, FF, DD, FF, FF, FF, CC, DD, EE, DD, FF, AA, FF, FF, BB, CC, BB, EE, FF, FF, BB, EE, CC, DD, FF, EE, CC, EE, DD, DD, EE, BB, DD, AA, FF, CC, DD, BB, CC, EE, FF, AA, AA, CC, DD, CC, EE, EE, CC, CC, EE, FF, BB, DD, BB, CC, BB, DD, FF, FF, EE, BB, DD, FF, EE, BB, CC, DD, DD, BB, AA, EE, DD, DD, DD, AA, BB, CC, BB, FF, BB, FF, EE, DD, EE, DD, EE, FF, CC, DD, EE, FF, BB, DD, FF, CC, DD, BB, DD, CC, CC, AA, FF, CC, FF, CC, DD, GG, DD, DD, DD, EE, DD, FF, DD, AA, EE, FF, EE, DD, BB, FF, EE, II, FF, FF, DD, EE, CC, FF, DD, BB, EE, BB, CC, FF, CC, EE, DD, DD, EE, BB, BB, CC, DD, FF, FF, CC, DD, CC, AA, CC, EE, BB, BB, EE, FF, EE, FF, BB, DD, CC, FF, EE, CC, FF, FF, EE, FF, FF, CC, CC, EE, EE, CC, DD, EE, AA, FF, EE, DD, FF, AA, FF, FF, DD, FF, FF, DD, AA, EE, FF, FF, AA, FF, CC, CC, EE, EE, EE]);
baseGameReels1.get(GameRTPLevel.RTP_80).set(2, [JJ, II, GG, II, GG, JJ, JJ, JJ, JJ, JJ, JJ, HH, GG, II, HH, HH, HH, II, HH, HH, GG, JJ, JJ, HH, JJ, GG, JJ, II, WD, HH, HH, II, GG, II, II, HH, JJ, HH, II, HH, II, JJ, II, JJ, JJ, HH, JJ, II, HH, JJ, JJ, HH, JJ, GG, GG, II, GG, II, II, HH, GG, HH, II, GG, JJ, JJ, WD, HH, JJ, HH, GG, GG, JJ, JJ, HH, JJ, JJ, BB, HH, HH, JJ, II, II, II, JJ, JJ, II, GG, GG, GG, GG, II, HH, II, JJ, HH, DD, II, HH, II, JJ, GG, GG, II, II, HH, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, JJ, JJ, HH, GG, JJ, JJ, JJ, HH, II, II, GG, GG, JJ, JJ, II, JJ, GG, JJ, HH, HH, JJ, II, GG, JJ, HH, HH, II, HH, JJ, HH, HH, HH, HH, GG, II, JJ, HH, II, HH, II, II, II, GG, II, GG, JJ, HH, II, HH, GG, JJ, JJ, II, GG, II, JJ, HH, JJ, II, JJ, GG, GG, JJ, JJ, JJ, II, II, HH, II, JJ, GG, HH, JJ, HH, CC, JJ, HH, JJ, JJ, JJ, II, JJ, GG, JJ, II, JJ, HH, JJ, JJ, JJ, JJ, GG, HH, HH, JJ, GG, II, JJ, II, JJ, II, II, II, II, II, JJ, II, GG, GG, GG, JJ, II, GG, GG, II, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, II, II, HH, GG, JJ, HH, II, HH, HH, HH, II, GG, FF, II, JJ, HH, GG, JJ, WD, JJ, JJ, WD, II, JJ, JJ, II, JJ, JJ, JJ, EE, II, JJ, HH, JJ, II, HH, JJ, JJ, II, HH, JJ, II, JJ, JJ, II, II, II, HH, GG, HH, GG, JJ, II, II, JJ, GG, AA, HH, GG, GG, II, JJ, II, JJ, JJ, HH, II, II, II, GG, HH, II, GG, JJ, JJ, II, HH, II, II, JJ, JJ, HH, WD, HH, HH, JJ, II, HH, JJ, II, JJ, II]);
baseGameReels1.get(GameRTPLevel.RTP_80).set(3, [EE, FF, CC, DD, EE, EE, CC, CC, DD, BB, DD, DD, BB, EE, FF, FF, EE, EE, FF, BB, CC, FF, BB, FF, CC, EE, FF, EE, FF, FF, DD, EE, DD, BB, BB, FF, WD, FF, CC, FF, FF, EE, DD, BB, EE, EE, FF, EE, FF, FF, WD, FF, DD, FF, AA, BB, FF, EE, FF, BB, BB, EE, FF, AA, FF, BB, AA, AA, FF, FF, FF, FF, EE, CC, CC, FF, CC, CC, FF, FF, EE, FF, DD, CC, FF, DD, DD, CC, FF, AA, FF, DD, WD, EE, FF, DD, DD, CC, FF, EE, FF, BB, EE, FF, FF, CC, BB, FF, FF, CC, FF, FF, AA, EE, CC, FF, FF, CC, EE, CC, FF, BB, EE, EE, FF, DD, EE, BB, CC, DD, DD, FF, DD, BB, EE, FF, DD, FF, DD, FF, DD, EE, CC, DD, FF, BB, BB, FF, DD, AA, EE, EE, DD, AA, CC, DD, DD, FF, II, EE, CC, CC, BB, CC, EE, AA, EE, FF, AA, EE, CC, DD, FF, FF, CC, CC, DD, DD, AA, FF, AA, DD, FF, WD, DD, EE, BB, DD, FF, AA, EE, DD, DD, BB, DD, DD, EE, BB, CC, CC, FF, EE, FF, EE, FF, EE, FF, FF, FF, FF, BB, BB, BB, EE, AA, EE, FF, CC, FF, AA, FF, EE, DD, EE, CC, DD, FF, EE, CC, EE, FF, EE, CC, FF, EE, BB, HH, BB, DD, AA, AA, DD, JJ, FF, DD, EE, DD, CC, CC, FF, FF, EE, DD, FF, CC, FF, EE, EE, DD, DD, FF, CC, EE, BB, EE, BB, CC, FF, FF, FF, FF, DD, DD, BB, FF, BB, EE, EE, BB, EE, FF, EE, BB, FF, EE, AA, EE, DD, DD, EE, FF, EE, AA, CC, EE, CC, EE, CC, EE, CC, EE, EE, EE, CC, FF, DD, DD, EE, FF, FF, EE, EE, DD, DD, FF, FF, FF, EE, CC, FF, EE, DD, EE, EE, CC, FF, FF, EE, EE, BB, DD, EE, FF, FF, EE, FF, FF, FF, DD, EE, CC, CC, AA, AA, CC, DD, EE, CC, EE, EE, FF, EE, DD, CC, DD, CC, BB, EE, AA, CC, EE, DD, DD, FF, FF, EE, GG, EE, FF, FF, EE, FF, FF, EE, CC, BB, FF, DD, AA, BB, BB, AA, EE, EE, DD, DD, DD, CC, CC, EE, DD, FF, CC, FF, EE, AA, FF, BB, FF, FF, FF, CC, CC, DD, BB, FF, CC, CC, FF, EE, WD, CC, BB, EE, DD, EE, FF, FF, FF, CC, DD, DD, EE, CC, CC, EE, FF, DD, FF, EE, DD, FF, EE, AA, BB, CC, EE, FF, BB, BB, AA, DD, EE, DD, FF, DD, DD, EE, AA, CC, DD, DD, DD, DD, BB, CC, FF, DD, DD, AA, DD, DD, CC, EE, FF, CC, BB, BB, DD, AA, EE, DD, BB, DD, FF, EE, EE, BB, EE, EE, CC, FF, BB, DD, DD, EE, DD, FF, FF]);
baseGameReels1.get(GameRTPLevel.RTP_80).set(4, [JJ, JJ, II, GG, JJ, GG, HH, WD, JJ, HH, GG, II, GG, DD, HH, GG, JJ, JJ, II, II, II, HH, GG, II, JJ, II, HH, HH, GG, II, II, II, JJ, JJ, JJ, JJ, JJ, HH, JJ, GG, II, HH, HH, II, II, JJ, HH, JJ, II, JJ, II, HH, JJ, GG, GG, II, HH, HH, II, HH, GG, II, JJ, II, HH, JJ, JJ, JJ, HH, GG, JJ, JJ, II, GG, JJ, II, GG, JJ, JJ, JJ, JJ, EE, HH, GG, JJ, GG, HH, II, JJ, HH, JJ, JJ, JJ, HH, JJ, GG, HH, II, GG, JJ, JJ, II, II, HH, HH, WD, II, II, HH, JJ, JJ, JJ, II, JJ, GG, II, JJ, II, HH, II, II, JJ, II, JJ, GG, JJ, HH, II, WD, JJ, II, HH, JJ, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, II, HH, JJ, GG, II, CC, JJ, AA, II, II, HH, HH, HH, II, JJ, JJ, JJ, HH, JJ, GG, GG, GG, II, JJ, JJ, II, JJ, JJ, II, GG, GG, JJ, II, GG, BB, JJ, JJ, HH, II, II, JJ, JJ, II, II, II, II, GG, II, II, JJ, II, GG, II, GG, GG, II, II, II, II, GG, II, JJ, HH, HH, JJ, JJ, JJ, II, HH, JJ, WD, HH, II, II, GG, HH, GG, JJ, JJ, II, GG, II, II, JJ, II, HH, HH, HH, II, JJ, JJ, JJ, JJ, II, II, JJ, JJ, HH, JJ, HH, JJ, JJ, GG, JJ, HH, GG, HH, JJ, GG, II, JJ, II, JJ, II, GG, II, FF, JJ, HH, HH, GG, HH, HH, II, HH, WD, JJ, HH, GG, GG, HH, II, JJ, JJ, JJ, HH, HH, HH, JJ, II, JJ, JJ, GG, HH, II, JJ, II, HH, HH, JJ, II, GG, HH, GG, JJ, HH, JJ, HH, HH, JJ, II, II, II, HH, II, HH, JJ, JJ, HH, JJ, JJ, GG, HH, JJ, JJ, II, II, II, GG, HH, II, GG, II, GG, HH, JJ, JJ, HH, II, GG]);
baseGameReels1.get(GameRTPLevel.RTP_80).set(5, [BB, FF, WD, FF, FF, BB, DD, CC, AA, EE, BB, GG, FF, FF, II, CC, EE, FF, FF, CC, FF, FF, EE, EE, FF, EE, CC, AA, FF, DD, FF, AA, FF, DD, AA, DD, FF, FF, WD, CC, EE, EE, BB, DD, BB, AA, FF, FF, FF, FF, AA, EE, CC, FF, FF, FF, DD, EE, CC, DD, CC, EE, FF, DD, FF, EE, CC, AA, FF, DD, FF, EE, BB, CC, CC, AA, EE, DD, BB, EE, CC, DD, DD, FF, EE, DD, DD, EE, CC, AA, FF, CC, DD, FF, DD, FF, DD, FF, FF, CC, EE, BB, EE, DD, FF, FF, FF, AA, BB, EE, CC, DD, DD, FF, FF, EE, CC, EE, EE, FF, EE, FF, DD, FF, FF, DD, EE, EE, AA, FF, AA, FF, EE, EE, EE, EE, EE, EE, EE, FF, DD, EE, EE, FF, FF, BB, FF, DD, FF, CC, BB, EE, FF, CC, CC, EE, DD, BB, HH, FF, AA, DD, FF, EE, EE, EE, DD, FF, EE, CC, FF, EE, EE, WD, EE, EE, DD, BB, CC, EE, BB, EE, FF, EE, CC, EE, CC, BB, EE, AA, BB, EE, FF, FF, AA, EE, FF, FF, FF, CC, FF, DD, DD, AA, EE, FF, FF, CC, AA, BB, EE, CC, FF, FF, EE, CC, CC, EE, BB, DD, EE, FF, EE, DD, DD, AA, CC, FF, DD, FF, FF, EE, DD, CC, CC, FF, CC, CC, CC, FF, CC, CC, DD, EE, EE, CC, DD, CC, EE, FF, FF, EE, DD, BB, FF, FF, FF, CC, DD, FF, FF, FF, FF, FF, CC, FF, FF, EE, DD, EE, CC, FF, BB, DD, BB, DD, DD, FF, BB, FF, DD, FF, EE, CC, FF, BB, EE, FF, FF, BB, EE, CC, AA, CC, DD, FF, EE, DD, CC, EE, EE, DD, DD, FF, EE, FF, FF, CC, FF, AA, BB, AA, EE, FF, BB, DD, CC, EE, FF, CC, EE, EE, DD, EE, DD, DD, EE, CC, WD, EE, CC, DD, DD, AA, BB, BB, AA, AA, BB, EE, EE, FF, EE, FF, DD, DD, BB, CC, EE, EE, BB, FF, EE, BB, DD, FF, BB, EE, BB, DD, FF, EE, CC, DD, FF, DD, DD, BB, BB, AA, BB, BB, EE, BB, CC, FF, DD, BB, DD, FF, BB, FF, AA, FF, CC, AA, CC, FF, EE, DD, CC, DD, CC, EE, BB, FF, CC, EE, EE, CC, EE, FF, FF, DD, FF, AA, EE, DD, CC, FF, BB, DD, DD, FF, DD, CC, FF, EE, WD, DD, EE, EE, DD, DD, DD, EE, DD, FF, DD, FF, FF, BB, FF, EE, FF, EE, FF, DD, DD, DD, FF, EE, EE, BB, EE, FF, EE, CC, AA, EE, EE, FF, DD, BB, BB, DD, BB, CC, FF, EE, FF, CC, DD, CC, EE, FF, AA, DD, DD, DD, FF, BB, BB, CC, EE, JJ, FF, EE, EE, CC, CC, CC, FF, DD, DD, FF, DD, DD, DD]);
baseGameReels1.get(GameRTPLevel.RTP_80).set(6, [JJ, JJ, JJ, JJ, HH, HH, HH, II, JJ, AA, GG, HH, GG, JJ, II, HH, JJ, JJ, II, HH, HH, HH, JJ, JJ, JJ, GG, JJ, JJ, HH, II, II, JJ, GG, II, JJ, HH, JJ, HH, GG, GG, II, II, II, II, HH, HH, JJ, EE, GG, II, II, GG, JJ, JJ, II, HH, II, JJ, II, II, JJ, HH, GG, GG, HH, GG, II, JJ, JJ, JJ, JJ, HH, GG, II, GG, JJ, HH, II, HH, II, JJ, JJ, HH, II, GG, GG, II, HH, HH, HH, GG, JJ, II, II, HH, II, JJ, JJ, HH, HH, JJ, HH, HH, II, JJ, HH, II, II, II, HH, II, II, II, II, HH, II, JJ, HH, GG, JJ, II, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, GG, II, JJ, HH, HH, JJ, GG, CC, II, JJ, II, II, II, JJ, II, GG, HH, HH, BB, HH, JJ, GG, HH, JJ, GG, II, II, JJ, II, JJ, HH, II, JJ, II, GG, II, II, GG, II, GG, JJ, JJ, HH, JJ, JJ, JJ, II, HH, II, JJ, II, JJ, JJ, GG, GG, HH, II, HH, HH, HH, GG, JJ, JJ, HH, HH, HH, II, II, GG, GG, HH, II, JJ, JJ, JJ, GG, GG, II, JJ, HH, JJ, JJ, GG, II, II, DD, JJ, JJ, II, II, JJ, JJ, JJ, HH, HH, JJ, II, JJ, JJ, II, JJ, II, JJ, II, JJ, II, GG, GG, JJ, GG, JJ, II, JJ, JJ, JJ, HH, II, HH, JJ, JJ, GG, GG, II, II, II, GG, II, II, HH, JJ, II, JJ, HH, GG, GG, HH, GG, HH, II, JJ, II, JJ, JJ, HH, HH, GG, II, JJ, II, HH, GG, GG, JJ, JJ, GG, HH, HH, GG, JJ, GG, II, II, JJ, HH, GG, II, JJ, JJ, JJ, JJ, II, JJ, II, JJ, JJ, JJ, HH, II, HH, II, JJ, II, HH, JJ, HH, II, JJ, HH, II, JJ, JJ, JJ, JJ, II, FF, GG, JJ]);

baseGameReels1.set(GameRTPLevel.RTP_90, new Map());
baseGameReels1.get(GameRTPLevel.RTP_90).set(1, [CC, FF, EE, CC, DD, DD, FF, FF, FF, FF, EE, FF, EE, EE, CC, DD, DD, FF, AA, EE, DD, EE, FF, BB, CC, AA, EE, FF, DD, FF, FF, EE, DD, BB, FF, EE, BB, EE, DD, FF, CC, DD, DD, DD, EE, FF, FF, FF, CC, DD, FF, FF, FF, AA, BB, FF, FF, DD, FF, DD, FF, FF, EE, DD, FF, EE, CC, FF, EE, FF, EE, DD, EE, EE, CC, CC, DD, EE, EE, BB, DD, FF, DD, DD, FF, CC, FF, FF, FF, EE, EE, EE, CC, EE, EE, CC, CC, DD, DD, CC, FF, EE, DD, AA, FF, CC, AA, EE, DD, EE, EE, BB, JJ, EE, AA, EE, DD, EE, FF, AA, EE, BB, FF, DD, EE, DD, BB, EE, CC, EE, EE, BB, DD, CC, FF, EE, EE, FF, EE, FF, FF, BB, EE, DD, EE, DD, BB, EE, CC, BB, EE, EE, EE, EE, DD, FF, EE, BB, FF, EE, FF, AA, FF, EE, DD, FF, AA, FF, EE, CC, DD, FF, BB, HH, EE, FF, CC, DD, FF, EE, FF, FF, FF, EE, FF, BB, FF, DD, CC, CC, AA, EE, CC, FF, FF, EE, FF, DD, AA, CC, BB, BB, FF, FF, DD, EE, EE, FF, FF, EE, EE, AA, BB, EE, FF, FF, EE, EE, BB, FF, CC, EE, DD, DD, BB, EE, FF, AA, DD, FF, AA, DD, DD, CC, DD, FF, CC, BB, CC, CC, FF, AA, BB, FF, EE, CC, CC, EE, AA, AA, DD, EE, DD, BB, EE, EE, DD, FF, BB, FF, DD, FF, EE, FF, FF, FF, FF, CC, CC, FF, EE, CC, FF, BB, FF, EE, FF, DD, DD, FF, BB, FF, CC, CC, CC, FF, DD, FF, FF, FF, CC, DD, EE, DD, FF, AA, FF, FF, BB, CC, BB, EE, FF, FF, BB, EE, CC, DD, FF, EE, CC, EE, DD, DD, EE, BB, DD, AA, FF, CC, DD, BB, CC, EE, FF, AA, AA, CC, DD, CC, EE, EE, CC, CC, EE, FF, BB, DD, BB, CC, BB, DD, FF, FF, EE, BB, DD, FF, EE, BB, CC, DD, DD, BB, AA, EE, DD, DD, DD, AA, BB, CC, BB, FF, BB, FF, EE, DD, EE, DD, EE, FF, CC, DD, EE, FF, BB, DD, FF, CC, DD, BB, DD, CC, CC, AA, FF, CC, FF, CC, DD, GG, DD, DD, DD, EE, DD, FF, DD, AA, EE, FF, EE, DD, BB, FF, EE, II, FF, FF, DD, EE, CC, FF, DD, BB, EE, BB, CC, FF, CC, EE, DD, DD, EE, BB, BB, CC, DD, FF, FF, CC, DD, CC, AA, CC, EE, BB, BB, EE, FF, EE, FF, BB, DD, CC, FF, EE, CC, FF, FF, EE, FF, FF, CC, CC, EE, EE, CC, DD, EE, AA, FF, EE, DD, FF, AA, FF, FF, DD, FF, FF, DD, AA, EE, FF, FF, AA, FF, CC, CC, EE, EE, EE]);
baseGameReels1.get(GameRTPLevel.RTP_90).set(2, [JJ, II, GG, II, GG, JJ, JJ, JJ, JJ, JJ, JJ, HH, GG, II, HH, HH, HH, II, HH, HH, GG, JJ, JJ, HH, JJ, GG, JJ, II, WD, HH, HH, II, GG, II, II, HH, JJ, HH, II, HH, II, JJ, II, JJ, JJ, HH, JJ, II, HH, JJ, JJ, HH, JJ, GG, GG, II, GG, II, II, HH, GG, HH, II, GG, JJ, JJ, WD, HH, JJ, HH, GG, GG, JJ, JJ, HH, JJ, JJ, BB, HH, HH, JJ, II, II, II, JJ, JJ, II, GG, GG, GG, GG, II, HH, II, JJ, HH, DD, II, HH, II, JJ, GG, GG, II, II, HH, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, JJ, JJ, HH, GG, JJ, JJ, JJ, HH, II, II, GG, GG, JJ, JJ, II, JJ, GG, JJ, HH, HH, JJ, II, GG, JJ, HH, HH, II, HH, JJ, HH, HH, HH, HH, GG, II, JJ, HH, II, HH, II, II, II, GG, II, GG, JJ, HH, II, HH, GG, JJ, JJ, II, GG, II, JJ, HH, JJ, II, JJ, GG, GG, JJ, JJ, JJ, II, II, HH, II, JJ, GG, HH, JJ, HH, CC, JJ, HH, JJ, JJ, JJ, II, JJ, GG, JJ, II, JJ, HH, JJ, JJ, JJ, JJ, GG, HH, HH, JJ, GG, II, JJ, II, JJ, II, II, II, II, II, JJ, II, GG, GG, GG, JJ, II, GG, GG, II, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, II, II, HH, GG, JJ, HH, II, HH, HH, HH, II, GG, FF, II, JJ, HH, GG, JJ, WD, JJ, JJ, WD, II, JJ, JJ, II, JJ, JJ, JJ, EE, II, JJ, HH, JJ, II, HH, JJ, JJ, II, HH, JJ, II, JJ, JJ, II, II, II, HH, GG, HH, GG, JJ, II, II, JJ, GG, AA, HH, GG, GG, II, JJ, II, JJ, JJ, HH, II, II, II, GG, HH, II, GG, JJ, JJ, II, HH, II, II, JJ, JJ, HH, WD, HH, HH, JJ, II, HH, JJ, II, JJ, II]);
baseGameReels1.get(GameRTPLevel.RTP_90).set(3, [EE, FF, CC, DD, EE, EE, CC, CC, DD, BB, DD, DD, BB, EE, FF, FF, EE, EE, FF, BB, CC, FF, BB, FF, CC, EE, FF, EE, FF, FF, DD, EE, DD, BB, BB, FF, WD, FF, CC, FF, FF, EE, DD, BB, EE, EE, FF, EE, FF, FF, WD, FF, DD, FF, AA, BB, FF, EE, FF, BB, BB, EE, FF, AA, FF, BB, AA, AA, FF, FF, FF, FF, EE, CC, CC, FF, CC, CC, FF, FF, EE, FF, DD, CC, FF, DD, DD, CC, FF, AA, FF, DD, WD, EE, FF, DD, DD, CC, FF, EE, FF, BB, EE, FF, FF, CC, BB, FF, FF, CC, FF, FF, AA, EE, CC, FF, FF, CC, EE, CC, FF, BB, EE, EE, FF, DD, EE, BB, CC, DD, DD, FF, DD, BB, EE, FF, DD, FF, DD, FF, DD, EE, CC, DD, FF, BB, BB, FF, DD, AA, EE, EE, DD, AA, CC, DD, DD, FF, II, EE, CC, CC, BB, CC, EE, AA, EE, FF, AA, EE, CC, DD, FF, FF, CC, CC, DD, DD, AA, FF, AA, DD, FF, WD, DD, EE, BB, DD, FF, AA, EE, DD, DD, BB, DD, DD, EE, BB, CC, CC, FF, EE, FF, EE, FF, EE, FF, FF, FF, FF, BB, BB, BB, EE, AA, EE, FF, CC, FF, AA, FF, EE, DD, EE, CC, DD, FF, EE, CC, EE, FF, EE, CC, FF, EE, BB, HH, BB, DD, AA, AA, DD, JJ, FF, DD, EE, DD, CC, CC, FF, FF, EE, DD, FF, CC, FF, EE, EE, DD, DD, FF, CC, EE, BB, EE, BB, CC, FF, FF, FF, FF, DD, DD, BB, FF, BB, EE, EE, BB, EE, FF, EE, BB, FF, EE, AA, EE, DD, DD, EE, FF, EE, AA, CC, EE, CC, EE, CC, EE, CC, EE, EE, EE, CC, FF, DD, DD, EE, FF, FF, EE, EE, DD, DD, FF, FF, FF, EE, CC, FF, EE, DD, EE, EE, CC, FF, FF, EE, EE, BB, DD, EE, FF, FF, EE, FF, FF, FF, DD, EE, CC, CC, AA, AA, CC, DD, EE, CC, EE, EE, FF, EE, DD, CC, DD, CC, BB, EE, AA, CC, EE, DD, DD, FF, FF, EE, GG, EE, FF, FF, EE, FF, FF, EE, CC, BB, FF, DD, AA, BB, BB, AA, EE, EE, DD, DD, DD, CC, CC, EE, DD, FF, CC, FF, EE, AA, FF, BB, FF, FF, FF, CC, CC, DD, BB, FF, CC, CC, FF, EE, WD, CC, BB, EE, DD, EE, FF, FF, FF, CC, DD, DD, EE, CC, CC, EE, FF, DD, FF, EE, DD, FF, EE, AA, BB, CC, EE, FF, BB, BB, AA, DD, EE, DD, FF, DD, DD, EE, AA, CC, DD, DD, DD, DD, BB, CC, FF, DD, DD, AA, DD, DD, CC, EE, FF, CC, BB, BB, DD, AA, EE, DD, BB, DD, FF, EE, EE, BB, EE, EE, CC, FF, BB, DD, DD, EE, DD, FF, FF]);
baseGameReels1.get(GameRTPLevel.RTP_90).set(4, [JJ, JJ, II, GG, JJ, GG, HH, WD, JJ, HH, GG, II, GG, DD, HH, GG, JJ, JJ, II, II, II, HH, GG, II, JJ, II, HH, HH, GG, II, II, II, JJ, JJ, JJ, JJ, JJ, HH, JJ, GG, II, HH, HH, II, II, JJ, HH, JJ, II, JJ, II, HH, JJ, GG, GG, II, HH, HH, II, HH, GG, II, JJ, II, HH, JJ, JJ, JJ, HH, GG, JJ, JJ, II, GG, JJ, II, GG, JJ, JJ, JJ, JJ, EE, HH, GG, JJ, GG, HH, II, JJ, HH, JJ, JJ, JJ, HH, JJ, GG, HH, II, GG, JJ, JJ, II, II, HH, HH, WD, II, II, HH, JJ, JJ, JJ, II, JJ, GG, II, JJ, II, HH, II, II, JJ, II, JJ, GG, JJ, HH, II, WD, JJ, II, HH, JJ, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, II, HH, JJ, GG, II, CC, JJ, AA, II, II, HH, HH, HH, II, JJ, JJ, JJ, HH, JJ, GG, GG, GG, II, JJ, JJ, II, JJ, JJ, II, GG, GG, JJ, II, GG, BB, JJ, JJ, HH, II, II, JJ, JJ, II, II, II, II, GG, II, II, JJ, II, GG, II, GG, GG, II, II, II, II, GG, II, JJ, HH, HH, JJ, JJ, JJ, II, HH, JJ, WD, HH, II, II, GG, HH, GG, JJ, JJ, II, GG, II, II, JJ, II, HH, HH, HH, II, JJ, JJ, JJ, JJ, II, II, JJ, JJ, HH, JJ, HH, JJ, JJ, GG, JJ, HH, GG, HH, JJ, GG, II, JJ, II, JJ, II, GG, II, FF, JJ, HH, HH, GG, HH, HH, II, HH, WD, JJ, HH, GG, GG, HH, II, JJ, JJ, JJ, HH, HH, HH, JJ, II, JJ, JJ, GG, HH, II, JJ, II, HH, HH, JJ, II, GG, HH, GG, JJ, HH, JJ, HH, HH, JJ, II, II, II, HH, II, HH, JJ, JJ, HH, JJ, JJ, GG, HH, JJ, JJ, II, II, II, GG, HH, II, GG, II, GG, HH, JJ, JJ, HH, II, GG]);
baseGameReels1.get(GameRTPLevel.RTP_90).set(5, [BB, FF, WD, FF, FF, BB, DD, CC, AA, EE, BB, GG, FF, FF, II, CC, EE, FF, FF, CC, FF, FF, EE, EE, FF, EE, CC, AA, FF, DD, FF, AA, FF, DD, AA, DD, FF, FF, WD, CC, EE, EE, BB, DD, BB, AA, FF, FF, FF, FF, AA, EE, CC, FF, FF, FF, DD, EE, CC, DD, CC, EE, FF, DD, FF, EE, CC, AA, FF, DD, FF, EE, BB, CC, CC, AA, EE, DD, BB, EE, CC, DD, DD, FF, EE, DD, DD, EE, CC, AA, FF, CC, DD, FF, DD, FF, DD, FF, FF, CC, EE, BB, EE, DD, FF, FF, FF, AA, BB, EE, CC, DD, DD, FF, FF, EE, CC, EE, EE, FF, EE, FF, DD, FF, FF, DD, EE, EE, AA, FF, AA, FF, EE, EE, EE, EE, EE, EE, EE, FF, DD, EE, EE, FF, FF, BB, FF, DD, FF, CC, BB, EE, FF, CC, CC, EE, DD, BB, HH, FF, AA, DD, FF, EE, EE, EE, DD, FF, EE, CC, FF, EE, EE, WD, EE, EE, DD, BB, CC, EE, BB, EE, FF, EE, CC, EE, CC, BB, EE, AA, BB, EE, FF, FF, AA, EE, FF, FF, FF, CC, FF, DD, DD, AA, EE, FF, FF, CC, AA, BB, EE, CC, FF, FF, EE, CC, CC, EE, BB, DD, EE, FF, EE, DD, DD, AA, CC, FF, DD, FF, FF, EE, DD, CC, CC, FF, CC, CC, CC, FF, CC, CC, DD, EE, EE, CC, DD, CC, EE, FF, FF, EE, DD, BB, FF, FF, FF, CC, DD, FF, FF, FF, FF, FF, CC, FF, FF, EE, DD, EE, CC, FF, BB, DD, BB, DD, DD, FF, BB, FF, DD, FF, EE, CC, FF, BB, EE, FF, FF, BB, EE, CC, AA, CC, DD, FF, EE, DD, CC, EE, EE, DD, DD, FF, EE, FF, FF, CC, FF, AA, BB, AA, EE, FF, BB, DD, CC, EE, FF, CC, EE, EE, DD, EE, DD, DD, EE, CC, WD, EE, CC, DD, DD, AA, BB, BB, AA, AA, BB, EE, EE, FF, EE, FF, DD, DD, BB, CC, EE, EE, BB, FF, EE, BB, DD, FF, BB, EE, BB, DD, FF, EE, CC, DD, FF, DD, DD, BB, BB, AA, BB, BB, EE, BB, CC, FF, DD, BB, DD, FF, BB, FF, AA, FF, CC, AA, CC, FF, EE, DD, CC, DD, CC, EE, BB, FF, CC, EE, EE, CC, EE, FF, FF, DD, FF, AA, EE, DD, CC, FF, BB, DD, DD, FF, DD, CC, FF, EE, WD, DD, EE, EE, DD, DD, DD, EE, DD, FF, DD, FF, FF, BB, FF, EE, FF, EE, FF, DD, DD, DD, FF, EE, EE, BB, EE, FF, EE, CC, AA, EE, EE, FF, DD, BB, BB, DD, BB, CC, FF, EE, FF, CC, DD, CC, EE, FF, AA, DD, DD, DD, FF, BB, BB, CC, EE, JJ, FF, EE, EE, CC, CC, CC, FF, DD, DD, FF, DD, DD, DD]);
baseGameReels1.get(GameRTPLevel.RTP_90).set(6, [JJ, JJ, JJ, JJ, HH, HH, HH, II, JJ, AA, GG, HH, GG, JJ, II, HH, JJ, JJ, II, HH, HH, HH, JJ, JJ, JJ, GG, JJ, JJ, HH, II, II, JJ, GG, II, JJ, HH, JJ, HH, GG, GG, II, II, II, II, HH, HH, JJ, EE, GG, II, II, GG, JJ, JJ, II, HH, II, JJ, II, II, JJ, HH, GG, GG, HH, GG, II, JJ, JJ, JJ, JJ, HH, GG, II, GG, JJ, HH, II, HH, II, JJ, JJ, HH, II, GG, GG, II, HH, HH, HH, GG, JJ, II, II, HH, II, JJ, JJ, HH, HH, JJ, HH, HH, II, JJ, HH, II, II, II, HH, II, II, II, II, HH, II, JJ, HH, GG, JJ, II, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, GG, II, JJ, HH, HH, JJ, GG, CC, II, JJ, II, II, II, JJ, II, GG, HH, HH, BB, HH, JJ, GG, HH, JJ, GG, II, II, JJ, II, JJ, HH, II, JJ, II, GG, II, II, GG, II, GG, JJ, JJ, HH, JJ, JJ, JJ, II, HH, II, JJ, II, JJ, JJ, GG, GG, HH, II, HH, HH, HH, GG, JJ, JJ, HH, HH, HH, II, II, GG, GG, HH, II, JJ, JJ, JJ, GG, GG, II, JJ, HH, JJ, JJ, GG, II, II, DD, JJ, JJ, II, II, JJ, JJ, JJ, HH, HH, JJ, II, JJ, JJ, II, JJ, II, JJ, II, JJ, II, GG, GG, JJ, GG, JJ, II, JJ, JJ, JJ, HH, II, HH, JJ, JJ, GG, GG, II, II, II, GG, II, II, HH, JJ, II, JJ, HH, GG, GG, HH, GG, HH, II, JJ, II, JJ, JJ, HH, HH, GG, II, JJ, II, HH, GG, GG, JJ, JJ, GG, HH, HH, GG, JJ, GG, II, II, JJ, HH, GG, II, JJ, JJ, JJ, JJ, II, JJ, II, JJ, JJ, JJ, HH, II, HH, II, JJ, II, HH, JJ, HH, II, JJ, HH, II, JJ, JJ, JJ, JJ, II, FF, GG, JJ]);

baseGameReels1.set(GameRTPLevel.RTP_95, new Map());
baseGameReels1.get(GameRTPLevel.RTP_95).set(1, [CC, FF, EE, CC, DD, DD, FF, FF, FF, FF, EE, FF, EE, EE, CC, DD, DD, FF, AA, EE, DD, EE, FF, BB, CC, AA, EE, FF, DD, FF, FF, EE, DD, BB, FF, EE, BB, EE, DD, FF, CC, DD, DD, DD, EE, FF, FF, FF, CC, DD, FF, FF, FF, AA, BB, FF, FF, DD, FF, DD, FF, FF, EE, DD, FF, EE, CC, FF, EE, FF, EE, DD, EE, EE, CC, CC, DD, EE, EE, BB, DD, FF, DD, DD, FF, CC, FF, FF, FF, EE, EE, EE, CC, EE, EE, CC, CC, DD, DD, CC, FF, EE, DD, AA, FF, CC, AA, EE, DD, EE, EE, BB, JJ, EE, AA, EE, DD, EE, FF, AA, EE, BB, FF, DD, EE, DD, BB, EE, CC, EE, EE, BB, DD, CC, FF, EE, EE, FF, EE, FF, FF, BB, EE, DD, EE, DD, BB, EE, CC, BB, EE, EE, EE, EE, DD, FF, EE, BB, FF, EE, FF, AA, FF, EE, DD, FF, AA, FF, EE, CC, DD, FF, BB, HH, EE, FF, CC, DD, FF, EE, FF, FF, FF, EE, FF, BB, FF, DD, CC, CC, AA, EE, CC, FF, FF, EE, FF, DD, AA, CC, BB, BB, FF, FF, DD, EE, EE, FF, FF, EE, EE, AA, BB, EE, FF, FF, EE, EE, BB, FF, CC, EE, DD, DD, BB, EE, FF, AA, DD, FF, AA, DD, DD, CC, DD, FF, CC, BB, CC, CC, FF, AA, BB, FF, EE, CC, CC, EE, AA, AA, DD, EE, DD, BB, EE, EE, DD, FF, BB, FF, DD, FF, EE, FF, FF, FF, FF, CC, CC, FF, EE, CC, FF, BB, FF, EE, FF, DD, DD, FF, BB, FF, CC, CC, CC, FF, DD, FF, FF, FF, CC, DD, EE, DD, FF, AA, FF, FF, BB, CC, BB, EE, FF, FF, BB, EE, CC, DD, FF, EE, CC, EE, DD, DD, EE, BB, DD, AA, FF, CC, DD, BB, CC, EE, FF, AA, AA, CC, DD, CC, EE, EE, CC, CC, EE, FF, BB, DD, BB, CC, BB, DD, FF, FF, EE, BB, DD, FF, EE, BB, CC, DD, DD, BB, AA, EE, DD, DD, DD, AA, BB, CC, BB, FF, BB, FF, EE, DD, EE, DD, EE, FF, CC, DD, EE, FF, BB, DD, FF, CC, DD, BB, DD, CC, CC, AA, FF, CC, FF, CC, DD, GG, DD, DD, DD, EE, DD, FF, DD, AA, EE, FF, EE, DD, BB, FF, EE, II, FF, FF, DD, EE, CC, FF, DD, BB, EE, BB, CC, FF, CC, EE, DD, DD, EE, BB, BB, CC, DD, FF, FF, CC, DD, CC, AA, CC, EE, BB, BB, EE, FF, EE, FF, BB, DD, CC, FF, EE, CC, FF, FF, EE, FF, FF, CC, CC, EE, EE, CC, DD, EE, AA, FF, EE, DD, FF, AA, FF, FF, DD, FF, FF, DD, AA, EE, FF, FF, AA, FF, CC, CC, EE, EE, EE]);
baseGameReels1.get(GameRTPLevel.RTP_95).set(2, [JJ, II, GG, II, GG, JJ, JJ, JJ, JJ, JJ, JJ, HH, GG, II, HH, HH, HH, II, HH, HH, GG, JJ, JJ, HH, JJ, GG, JJ, II, WD, HH, HH, II, GG, II, II, HH, JJ, HH, II, HH, II, JJ, II, JJ, JJ, HH, JJ, II, HH, JJ, JJ, HH, JJ, GG, GG, II, GG, II, II, HH, GG, HH, II, GG, JJ, JJ, WD, HH, JJ, HH, GG, GG, JJ, JJ, HH, JJ, JJ, BB, HH, HH, JJ, II, II, II, JJ, JJ, II, GG, GG, GG, GG, II, HH, II, JJ, HH, DD, II, HH, II, JJ, GG, GG, II, II, HH, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, JJ, JJ, HH, GG, JJ, JJ, JJ, HH, II, II, GG, GG, JJ, JJ, II, JJ, GG, JJ, HH, HH, JJ, II, GG, JJ, HH, HH, II, HH, JJ, HH, HH, HH, HH, GG, II, JJ, HH, II, HH, II, II, II, GG, II, GG, JJ, HH, II, HH, GG, JJ, JJ, II, GG, II, JJ, HH, JJ, II, JJ, GG, GG, JJ, JJ, JJ, II, II, HH, II, JJ, GG, HH, JJ, HH, CC, JJ, HH, JJ, JJ, JJ, II, JJ, GG, JJ, II, JJ, HH, JJ, JJ, JJ, JJ, GG, HH, HH, JJ, GG, II, JJ, II, JJ, II, II, II, II, II, JJ, II, GG, GG, GG, JJ, II, GG, GG, II, JJ, JJ, JJ, JJ, II, HH, II, II, JJ, II, II, HH, GG, JJ, HH, II, HH, HH, HH, II, GG, FF, II, JJ, HH, GG, JJ, WD, JJ, JJ, WD, II, JJ, JJ, II, JJ, JJ, JJ, EE, II, JJ, HH, JJ, II, HH, JJ, JJ, II, HH, JJ, II, JJ, JJ, II, II, II, HH, GG, HH, GG, JJ, II, II, JJ, GG, AA, HH, GG, GG, II, JJ, II, JJ, JJ, HH, II, II, II, GG, HH, II, GG, JJ, JJ, II, HH, II, II, JJ, JJ, HH, WD, HH, HH, JJ, II, HH, JJ, II, JJ, II]);
baseGameReels1.get(GameRTPLevel.RTP_95).set(3, [EE, FF, CC, DD, EE, EE, CC, CC, DD, BB, DD, DD, BB, EE, FF, FF, EE, EE, FF, BB, CC, FF, BB, FF, CC, EE, FF, EE, FF, FF, DD, EE, DD, BB, BB, FF, WD, FF, CC, FF, FF, EE, DD, BB, EE, EE, FF, EE, FF, FF, WD, FF, DD, FF, AA, BB, FF, EE, FF, BB, BB, EE, FF, AA, FF, BB, AA, AA, FF, FF, FF, FF, EE, CC, CC, FF, CC, CC, FF, FF, EE, FF, DD, CC, FF, DD, DD, CC, FF, AA, FF, DD, WD, EE, FF, DD, DD, CC, FF, EE, FF, BB, EE, FF, FF, CC, BB, FF, FF, CC, FF, FF, AA, EE, CC, FF, FF, CC, EE, CC, FF, BB, EE, EE, FF, DD, EE, BB, CC, DD, DD, FF, DD, BB, EE, FF, DD, FF, DD, FF, DD, EE, CC, DD, FF, BB, BB, FF, DD, AA, EE, EE, DD, AA, CC, DD, DD, FF, II, EE, CC, CC, BB, CC, EE, AA, EE, FF, AA, EE, CC, DD, FF, FF, CC, CC, DD, DD, AA, FF, AA, DD, FF, WD, DD, EE, BB, DD, FF, AA, EE, DD, DD, BB, DD, DD, EE, BB, CC, CC, FF, EE, FF, EE, FF, EE, FF, FF, FF, FF, BB, BB, BB, EE, AA, EE, FF, CC, FF, AA, FF, EE, DD, EE, CC, DD, FF, EE, CC, EE, FF, EE, CC, FF, EE, BB, HH, BB, DD, AA, AA, DD, JJ, FF, DD, EE, DD, CC, CC, FF, FF, EE, DD, FF, CC, FF, EE, EE, DD, DD, FF, CC, EE, BB, EE, BB, CC, FF, FF, FF, FF, DD, DD, BB, FF, BB, EE, EE, BB, EE, FF, EE, BB, FF, EE, AA, EE, DD, DD, EE, FF, EE, AA, CC, EE, CC, EE, CC, EE, CC, EE, EE, EE, CC, FF, DD, DD, EE, FF, FF, EE, EE, DD, DD, FF, FF, FF, EE, CC, FF, EE, DD, EE, EE, CC, FF, FF, EE, EE, BB, DD, EE, FF, FF, EE, FF, FF, FF, DD, EE, CC, CC, AA, AA, CC, DD, EE, CC, EE, EE, FF, EE, DD, CC, DD, CC, BB, EE, AA, CC, EE, DD, DD, FF, FF, EE, GG, EE, FF, FF, EE, FF, FF, EE, CC, BB, FF, DD, AA, BB, BB, AA, EE, EE, DD, DD, DD, CC, CC, EE, DD, FF, CC, FF, EE, AA, FF, BB, FF, FF, FF, CC, CC, DD, BB, FF, CC, CC, FF, EE, WD, CC, BB, EE, DD, EE, FF, FF, FF, CC, DD, DD, EE, CC, CC, EE, FF, DD, FF, EE, DD, FF, EE, AA, BB, CC, EE, FF, BB, BB, AA, DD, EE, DD, FF, DD, DD, EE, AA, CC, DD, DD, DD, DD, BB, CC, FF, DD, DD, AA, DD, DD, CC, EE, FF, CC, BB, BB, DD, AA, EE, DD, BB, DD, FF, EE, EE, BB, EE, EE, CC, FF, BB, DD, DD, EE, DD, FF, FF]);
baseGameReels1.get(GameRTPLevel.RTP_95).set(4, [JJ, JJ, II, GG, JJ, GG, HH, WD, JJ, HH, GG, II, GG, DD, HH, GG, JJ, JJ, II, II, II, HH, GG, II, JJ, II, HH, HH, GG, II, II, II, JJ, JJ, JJ, JJ, JJ, HH, JJ, GG, II, HH, HH, II, II, JJ, HH, JJ, II, JJ, II, HH, JJ, GG, GG, II, HH, HH, II, HH, GG, II, JJ, II, HH, JJ, JJ, JJ, HH, GG, JJ, JJ, II, GG, JJ, II, GG, JJ, JJ, JJ, JJ, EE, HH, GG, JJ, GG, HH, II, JJ, HH, JJ, JJ, JJ, HH, JJ, GG, HH, II, GG, JJ, JJ, II, II, HH, HH, WD, II, II, HH, JJ, JJ, JJ, II, JJ, GG, II, JJ, II, HH, II, II, JJ, II, JJ, GG, JJ, HH, II, WD, JJ, II, HH, JJ, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, II, HH, JJ, GG, II, CC, JJ, AA, II, II, HH, HH, HH, II, JJ, JJ, JJ, HH, JJ, GG, GG, GG, II, JJ, JJ, II, JJ, JJ, II, GG, GG, JJ, II, GG, BB, JJ, JJ, HH, II, II, JJ, JJ, II, II, II, II, GG, II, II, JJ, II, GG, II, GG, GG, II, II, II, II, GG, II, JJ, HH, HH, JJ, JJ, JJ, II, HH, JJ, WD, HH, II, II, GG, HH, GG, JJ, JJ, II, GG, II, II, JJ, II, HH, HH, HH, II, JJ, JJ, JJ, JJ, II, II, JJ, JJ, HH, JJ, HH, JJ, JJ, GG, JJ, HH, GG, HH, JJ, GG, II, JJ, II, JJ, II, GG, II, FF, JJ, HH, HH, GG, HH, HH, II, HH, WD, JJ, HH, GG, GG, HH, II, JJ, JJ, JJ, HH, HH, HH, JJ, II, JJ, JJ, GG, HH, II, JJ, II, HH, HH, JJ, II, GG, HH, GG, JJ, HH, JJ, HH, HH, JJ, II, II, II, HH, II, HH, JJ, JJ, HH, JJ, JJ, GG, HH, JJ, JJ, II, II, II, GG, HH, II, GG, II, GG, HH, JJ, JJ, HH, II, GG]);
baseGameReels1.get(GameRTPLevel.RTP_95).set(5, [BB, FF, WD, FF, FF, BB, DD, CC, AA, EE, BB, GG, FF, FF, II, CC, EE, FF, FF, CC, FF, FF, EE, EE, FF, EE, CC, AA, FF, DD, FF, AA, FF, DD, AA, DD, FF, FF, WD, CC, EE, EE, BB, DD, BB, AA, FF, FF, FF, FF, AA, EE, CC, FF, FF, FF, DD, EE, CC, DD, CC, EE, FF, DD, FF, EE, CC, AA, FF, DD, FF, EE, BB, CC, CC, AA, EE, DD, BB, EE, CC, DD, DD, FF, EE, DD, DD, EE, CC, AA, FF, CC, DD, FF, DD, FF, DD, FF, FF, CC, EE, BB, EE, DD, FF, FF, FF, AA, BB, EE, CC, DD, DD, FF, FF, EE, CC, EE, EE, FF, EE, FF, DD, FF, FF, DD, EE, EE, AA, FF, AA, FF, EE, EE, EE, EE, EE, EE, EE, FF, DD, EE, EE, FF, FF, BB, FF, DD, FF, CC, BB, EE, FF, CC, CC, EE, DD, BB, HH, FF, AA, DD, FF, EE, EE, EE, DD, FF, EE, CC, FF, EE, EE, WD, EE, EE, DD, BB, CC, EE, BB, EE, FF, EE, CC, EE, CC, BB, EE, AA, BB, EE, FF, FF, AA, EE, FF, FF, FF, CC, FF, DD, DD, AA, EE, FF, FF, CC, AA, BB, EE, CC, FF, FF, EE, CC, CC, EE, BB, DD, EE, FF, EE, DD, DD, AA, CC, FF, DD, FF, FF, EE, DD, CC, CC, FF, CC, CC, CC, FF, CC, CC, DD, EE, EE, CC, DD, CC, EE, FF, FF, EE, DD, BB, FF, FF, FF, CC, DD, FF, FF, FF, FF, FF, CC, FF, FF, EE, DD, EE, CC, FF, BB, DD, BB, DD, DD, FF, BB, FF, DD, FF, EE, CC, FF, BB, EE, FF, FF, BB, EE, CC, AA, CC, DD, FF, EE, DD, CC, EE, EE, DD, DD, FF, EE, FF, FF, CC, FF, AA, BB, AA, EE, FF, BB, DD, CC, EE, FF, CC, EE, EE, DD, EE, DD, DD, EE, CC, WD, EE, CC, DD, DD, AA, BB, BB, AA, AA, BB, EE, EE, FF, EE, FF, DD, DD, BB, CC, EE, EE, BB, FF, EE, BB, DD, FF, BB, EE, BB, DD, FF, EE, CC, DD, FF, DD, DD, BB, BB, AA, BB, BB, EE, BB, CC, FF, DD, BB, DD, FF, BB, FF, AA, FF, CC, AA, CC, FF, EE, DD, CC, DD, CC, EE, BB, FF, CC, EE, EE, CC, EE, FF, FF, DD, FF, AA, EE, DD, CC, FF, BB, DD, DD, FF, DD, CC, FF, EE, WD, DD, EE, EE, DD, DD, DD, EE, DD, FF, DD, FF, FF, BB, FF, EE, FF, EE, FF, DD, DD, DD, FF, EE, EE, BB, EE, FF, EE, CC, AA, EE, EE, FF, DD, BB, BB, DD, BB, CC, FF, EE, FF, CC, DD, CC, EE, FF, AA, DD, DD, DD, FF, BB, BB, CC, EE, JJ, FF, EE, EE, CC, CC, CC, FF, DD, DD, FF, DD, DD, DD]);
baseGameReels1.get(GameRTPLevel.RTP_95).set(6, [JJ, JJ, JJ, JJ, HH, HH, HH, II, JJ, AA, GG, HH, GG, JJ, II, HH, JJ, JJ, II, HH, HH, HH, JJ, JJ, JJ, GG, JJ, JJ, HH, II, II, JJ, GG, II, JJ, HH, JJ, HH, GG, GG, II, II, II, II, HH, HH, JJ, EE, GG, II, II, GG, JJ, JJ, II, HH, II, JJ, II, II, JJ, HH, GG, GG, HH, GG, II, JJ, JJ, JJ, JJ, HH, GG, II, GG, JJ, HH, II, HH, II, JJ, JJ, HH, II, GG, GG, II, HH, HH, HH, GG, JJ, II, II, HH, II, JJ, JJ, HH, HH, JJ, HH, HH, II, JJ, HH, II, II, II, HH, II, II, II, II, HH, II, JJ, HH, GG, JJ, II, JJ, JJ, JJ, HH, JJ, JJ, JJ, II, GG, II, JJ, HH, HH, JJ, GG, CC, II, JJ, II, II, II, JJ, II, GG, HH, HH, BB, HH, JJ, GG, HH, JJ, GG, II, II, JJ, II, JJ, HH, II, JJ, II, GG, II, II, GG, II, GG, JJ, JJ, HH, JJ, JJ, JJ, II, HH, II, JJ, II, JJ, JJ, GG, GG, HH, II, HH, HH, HH, GG, JJ, JJ, HH, HH, HH, II, II, GG, GG, HH, II, JJ, JJ, JJ, GG, GG, II, JJ, HH, JJ, JJ, GG, II, II, DD, JJ, JJ, II, II, JJ, JJ, JJ, HH, HH, JJ, II, JJ, JJ, II, JJ, II, JJ, II, JJ, II, GG, GG, JJ, GG, JJ, II, JJ, JJ, JJ, HH, II, HH, JJ, JJ, GG, GG, II, II, II, GG, II, II, HH, JJ, II, JJ, HH, GG, GG, HH, GG, HH, II, JJ, II, JJ, JJ, HH, HH, GG, II, JJ, II, HH, GG, GG, JJ, JJ, GG, HH, HH, GG, JJ, GG, II, II, JJ, HH, GG, II, JJ, JJ, JJ, JJ, II, JJ, II, JJ, JJ, JJ, HH, II, HH, II, JJ, II, HH, JJ, HH, II, JJ, HH, II, JJ, JJ, JJ, JJ, II, FF, GG, JJ]);


function createReelRandomMap60(randomPools) {
  const reelRandomMap = {};
  reelRandomMap[0] = randomPools.reel1_at_0_62;
  reelRandomMap[1] = randomPools.reel2_at_0_62;
  reelRandomMap[2] = randomPools.reel3_at_0_62;
  reelRandomMap[3] = randomPools.reel4_at_0_62;
  reelRandomMap[4] = randomPools.reel5_at_0_62;
  reelRandomMap[5] = randomPools.reel6_at_0_62;
  return reelRandomMap;
}

function createReelRandomMap70(randomPools) {
  const reelRandomMap = {};
  reelRandomMap[0] = randomPools.reel1_at_0_62;
  reelRandomMap[1] = randomPools.reel2_at_0_62;
  reelRandomMap[2] = randomPools.reel3_at_0_62;
  reelRandomMap[3] = randomPools.reel4_at_0_62;
  reelRandomMap[4] = randomPools.reel5_at_0_62;
  reelRandomMap[5] = randomPools.reel6_at_0_62;
  return reelRandomMap;
}

function createReelRandomMap80(randomPools) {
  const reelRandomMap = {};
  reelRandomMap[0] = randomPools.reel1_at_0_62;
  reelRandomMap[1] = randomPools.reel2_at_0_62;
  reelRandomMap[2] = randomPools.reel3_at_0_62;
  reelRandomMap[3] = randomPools.reel4_at_0_62;
  reelRandomMap[4] = randomPools.reel5_at_0_62;
  reelRandomMap[5] = randomPools.reel6_at_0_62;
  return reelRandomMap;
}

function createReelRandomMap90(randomPools) {
  const reelRandomMap = {};
  reelRandomMap[0] = randomPools.reel1_at_0_62;
  reelRandomMap[1] = randomPools.reel2_at_0_62;
  reelRandomMap[2] = randomPools.reel3_at_0_62;
  reelRandomMap[3] = randomPools.reel4_at_0_62;
  reelRandomMap[4] = randomPools.reel5_at_0_62;
  reelRandomMap[5] = randomPools.reel6_at_0_62;
  return reelRandomMap;
}

function createReelRandomMap95(randomPools) {
  const reelRandomMap = {};
  reelRandomMap[0] = randomPools.reel1_at_0_62;
  reelRandomMap[1] = randomPools.reel2_at_0_62;
  reelRandomMap[2] = randomPools.reel3_at_0_62;
  reelRandomMap[3] = randomPools.reel4_at_0_62;
  reelRandomMap[4] = randomPools.reel5_at_0_62;
  reelRandomMap[5] = randomPools.reel6_at_0_62;
  return reelRandomMap;
}

function createReelRandomMap(rtpLevel, randomPools) {
  switch (rtpLevel) {
    case 1:
      return createReelRandomMap60(randomPools);
    case 2:
      return createReelRandomMap70(randomPools);
    case 3:
      return createReelRandomMap80(randomPools);
    case 4:
      return createReelRandomMap90(randomPools);
    case 5:
      return createReelRandomMap95(randomPools);
    default:
      throw new Error(`RTP level ${rtpLevel} not recognized`);
  }
}

function createReelMap(rtpLevel) {
  
  switch (rtpLevel) {
    case 1:
      return baseGameReels1.get(GameRTPLevel.RTP_60);
    case 2:
      return baseGameReels1.get(GameRTPLevel.RTP_70);
    case 3:
      return baseGameReels1.get(GameRTPLevel.RTP_80)
    case 4:
      return baseGameReels1.get(GameRTPLevel.RTP_90)
    case 5:
      return baseGameReels1.get(GameRTPLevel.RTP_95)
    default:
      throw new Error(`RTP level ${rtpLevel} not recognized`);
  }
}


 
 
module.exports = {
  baseGameReels: baseGameReels1,
  createReelRandomMap,
  createReelMap
};