const FREE_GAME = true;
const FREE_GAME_RETRIGGER = false;
const WHEEL_BONUS = false;
const BASE_RESPIN = true;
const FREE_GAME_TRIGGER = 3;
const BONUS_GAME_TRIGGER = 3;

module.exports = { FREE_GAME_TRIGGER, BONUS_GAME_TRIGGER, FREE_GAME, FREE_GAME_RETRIGGER, WHEEL_BONUS, BASE_RESPIN };
